<?php

namespace Modules\Courses\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Courses\Models\Course;

class CoursesDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $courses = [

            // =========================
            // Core Courses (University)
            // =========================
            [
                'code' => 'GEN-C001',
                'name' => 'English Language',
                'name_ar' => 'اللغة الإنجليزية',
                'min_credits' => 0,
                'requirement' => 'university',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'freshman',
            ],
            [
                'code' => 'GEN-C002',
                'name' => 'Introduction to Computers',
                'name_ar' => 'مقدمة في الحاسبات',
                'min_credits' => 0,
                'requirement' => 'university',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'freshman',
            ],
            [
                'code' => 'GEN-C101',
                'name' => 'Human Rights',
                'name_ar' => 'حقوق الإنسان',
                'min_credits' => 0,
                'requirement' => 'university',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'sophomore',
            ],
            [
                'code' => 'GEN-C102',
                'name' => 'Project Management',
                'name_ar' => 'إدارة المشاريع',
                'min_credits' => 0,
                'requirement' => 'university',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'sophomore',
            ],
            [
                'code' => 'GEN-C201',
                'name' => 'Presentation Skills',
                'name_ar' => 'مهارات العرض',
                'min_credits' => 0,
                'requirement' => 'university',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'junior',
            ],
            [
                'code' => 'GEN-C202',
                'name' => 'Foundation of Economics',
                'name_ar' => 'أساسيات الاقتصاد',
                'min_credits' => 0,
                'requirement' => 'university',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'junior',
            ],
            [
                'code' => 'GEN-C301',
                'name' => 'Writing Technical Report',
                'name_ar' => 'كتابة التقارير الفنية',
                'min_credits' => 0,
                'requirement' => 'university',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'senior-1',
            ],

            // ============================
            // Elected Courses (University)
            // ============================
            [
                'code' => 'GEN-C003',
                'name' => 'English Oral Communication and Pronunciation',
                'name_ar' => 'التواصل الشفهي باللغة الإنجليزية والنطق',
                'min_credits' => 0,
                'requirement' => 'university',
                'type' => 'elected',
                'credits' => 2,
                'full_mark' => 100,
                'level' => 'freshman',
            ],
            [
                'code' => 'GEN-C103',
                'name' => 'Critical Thinking',
                'name_ar' => 'التفكير النقدي',
                'min_credits' => 0,
                'requirement' => 'university',
                'type' => 'elected',
                'credits' => 2,
                'full_mark' => 100,
                'level' => 'sophomore',
            ],
            [
                'code' => 'GEN-C203',
                'name' => 'Accounting',
                'name_ar' => 'المحاسبة',
                'min_credits' => 0,
                'requirement' => 'university',
                'type' => 'elected',
                'credits' => 2,
                'full_mark' => 100,
                'level' => 'junior',
            ],
            [
                'code' => 'GEN-C204',
                'name' => 'Marketing',
                'name_ar' => 'التسويق',
                'min_credits' => 0,
                'requirement' => 'university',
                'type' => 'elected',
                'credits' => 2,
                'full_mark' => 100,
                'level' => 'junior',
            ],
            [
                'code' => 'GEN-C205',
                'name' => 'Risk Management',
                'name_ar' => 'إدارة المخاطر',
                'min_credits' => 0,
                'requirement' => 'university',
                'type' => 'elected',
                'credits' => 2,
                'full_mark' => 100,
                'level' => 'junior',
            ],
            [
                'code' => 'GEN-C206',
                'name' => 'Engineering Ethics and Skills',
                'name_ar' => 'أخلاقيات الهندسة والمهارات',
                'min_credits' => 0,
                'requirement' => 'university',
                'type' => 'elected',
                'credits' => 2,
                'full_mark' => 100,
                'level' => 'junior',
            ],
            [
                'code' => 'GEN-C207',
                'name' => 'Engineering Economy',
                'name_ar' => 'اقتصاديات الهندسة',
                'min_credits' => 0,
                'requirement' => 'university',
                'type' => 'elected',
                'credits' => 2,
                'full_mark' => 100,
                'level' => 'junior',
            ],

            // ============================
            // Core Courses (Faculty)
            // ============================
            [
                'code' => 'FAC-C001',
                'name' => 'Mathematics (1)',
                'name_ar' => 'الرياضيات (1)',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'freshman',
            ],
            [
                'code' => 'FAC-C002',
                'name' => 'Physics (1)',
                'name_ar' => 'الفيزياء (1)',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'freshman',
            ],
            [
                'code' => 'FAC-C003',
                'name' => 'History of Engineering Science',
                'name_ar' => 'تاريخ العلوم الهندسية',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'freshman',
            ],
            [
                'code' => 'FAC-C004',
                'name' => 'Mathematics (2)',
                'name_ar' => 'الرياضيات (2)',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'sophomore',
            ],
            [
                'code' => 'FAC-C005',
                'name' => 'Chemistry',
                'name_ar' => 'الكيمياء',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'sophomore',
            ],
            [
                'code' => 'FAC-C006',
                'name' => 'Physics (2)',
                'name_ar' => 'الفيزياء (2)',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'sophomore',
            ],
            [
                'code' => 'FAC-C007',
                'name' => 'Applied Mechanics',
                'name_ar' => 'الميكانيكا التطبيقية',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'junior',
            ],
            [
                'code' => 'FAC-C008',
                'name' => 'Manufacturing Engineering',
                'name_ar' => 'هندسة التصنيع',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'core',
                'credits' => 2,
                'full_mark' => 100,
                'level' => 'junior',
            ],
            [
                'code' => 'FAC-C009',
                'name' => 'Engineering Drawing',
                'name_ar' => 'الرسم الهندسي',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'core',
                'credits' => 2,
                'full_mark' => 100,
                'level' => 'junior',
            ],
            [
                'code' => 'FAC-C010',
                'name' => 'Computer Language and Applications',
                'name_ar' => 'لغات الحاسوب وتطبيقاتها',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'junior',
            ],
            [
                'code' => 'FAC-C101',
                'name' => 'Probability and Statistics',
                'name_ar' => 'الاحتمالات والإحصاء',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'core',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'senior-1',
            ],
            [
                'code' => 'FAC-C401',
                'name' => 'Graduation Project',
                'name_ar' => 'مشروع التخرج',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'core',
                'credits' => 5,
                'full_mark' => 100,
                'level' => 'senior-2',
            ],

            // =========================
            // Elected Courses (Faculty)
            // =========================
            [
                'code' => 'FAC-C102',
                'name' => 'Numerical Calculations',
                'name_ar' => 'الحسابات العددية',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'elected',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'sophomore',
            ],
            [
                'code' => 'FAC-C103',
                'name' => 'Advanced Mathematics',
                'name_ar' => 'الرياضيات المتقدمة',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'elected',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'sophomore',
            ],
            [
                'code' => 'FAC-C104',
                'name' => 'Information Technology Systems',
                'name_ar' => 'أنظمة تكنولوجيا المعلومات',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'elected',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'sophomore',
            ],
            [
                'code' => 'FAC-C105',
                'name' => 'Statistical Methods',
                'name_ar' => 'الطرق الإحصائية',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'elected',
                'credits' => 2,
                'full_mark' => 100,
                'level' => 'sophomore',
            ],
            [
                'code' => 'FAC-C106',
                'name' => 'Discrete Mathematics',
                'name_ar' => 'الرياضيات المتقطعة',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'elected',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'sophomore',
            ],
            [
                'code' => 'FAC-C107',
                'name' => 'Energy Conversion',
                'name_ar' => 'تحويل الطاقة',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'elected',
                'credits' => 2,
                'full_mark' => 100,
                'level' => 'sophomore',
            ],
            [
                'code' => 'FAC-C201',
                'name' => 'System Modeling and Simulation',
                'name_ar' => 'نمذجة النظم والمحاكاة',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'elected',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'junior',
            ],
            [
                'code' => 'FAC-C202',
                'name' => 'Linear Programming',
                'name_ar' => 'البرمجة الخطية',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'elected',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'junior',
            ],
            [
                'code' => 'FAC-C203',
                'name' => 'Data Acquisition Systems',
                'name_ar' => 'أنظمة اكتساب البيانات',
                'min_credits' => 0,
                'requirement' => 'faculty',
                'type' => 'elected',
                'credits' => 3,
                'full_mark' => 100,
                'level' => 'junior',
            ],

            // =========================
            // Core Courses (Specialization ECE)
            // =========================

        ];

        foreach ($courses as $course) {
            Course::create($course);
        }
    }
}
